//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1873
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace We7.CMS.Web.Admin.ContentModel.Controls.Page {


    public partial class SimpleImage
    {
        protected global::System.Web.UI.WebControls.HiddenField ImageValue;
        protected global::System.Web.UI.WebControls.FileUpload fuImage;
        protected global::System.Web.UI.WebControls.Image imgCurrentImage;
        protected global::System.Web.UI.WebControls.Literal ltlMsg;
    }
}
