//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.235 版自动生成。
// 
#pragma warning disable 1591

namespace We7.CMS.ShopService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShopServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ShopService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecommendStoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecommendProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecommendProductByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyPluginsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPluginsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPluginsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisteSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRegistedProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadNotRegistedProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncryptPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ShopService() {
            this.Url = global::We7.CMS.Properties.Settings.Default.We7_CMS_Utils_ShopService_ShopService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event GetRecommendStoreCompletedEventHandler GetRecommendStoreCompleted;
        
        /// <remarks/>
        public event GetRecommendProductCompletedEventHandler GetRecommendProductCompleted;
        
        /// <remarks/>
        public event GetRecommendProductByTypeCompletedEventHandler GetRecommendProductByTypeCompleted;
        
        /// <remarks/>
        public event InsertOrdersCompletedEventHandler InsertOrdersCompleted;
        
        /// <remarks/>
        public event GetMyPluginsCompletedEventHandler GetMyPluginsCompleted;
        
        /// <remarks/>
        public event GetPluginsCompletedEventHandler GetPluginsCompleted;
        
        /// <remarks/>
        public event QueryPluginsCompletedEventHandler QueryPluginsCompleted;
        
        /// <remarks/>
        public event CheckSiteCompletedEventHandler CheckSiteCompleted;
        
        /// <remarks/>
        public event RegisteSiteCompletedEventHandler RegisteSiteCompleted;
        
        /// <remarks/>
        public event LoadRegistedProductsCompletedEventHandler LoadRegistedProductsCompleted;
        
        /// <remarks/>
        public event LoadNotRegistedProductsCompletedEventHandler LoadNotRegistedProductsCompleted;
        
        /// <remarks/>
        public event RegisteProductCompletedEventHandler RegisteProductCompleted;
        
        /// <remarks/>
        public event EncryptPasswordCompletedEventHandler EncryptPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecommendStore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StoreModel[] GetRecommendStore(int count) {
            object[] results = this.Invoke("GetRecommendStore", new object[] {
                        count});
            return ((StoreModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecommendStoreAsync(int count) {
            this.GetRecommendStoreAsync(count, null);
        }
        
        /// <remarks/>
        public void GetRecommendStoreAsync(int count, object userState) {
            if ((this.GetRecommendStoreOperationCompleted == null)) {
                this.GetRecommendStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecommendStoreOperationCompleted);
            }
            this.InvokeAsync("GetRecommendStore", new object[] {
                        count}, this.GetRecommendStoreOperationCompleted, userState);
        }
        
        private void OnGetRecommendStoreOperationCompleted(object arg) {
            if ((this.GetRecommendStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecommendStoreCompleted(this, new GetRecommendStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecommendProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetRecommendProduct(int count) {
            object[] results = this.Invoke("GetRecommendProduct", new object[] {
                        count});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecommendProductAsync(int count) {
            this.GetRecommendProductAsync(count, null);
        }
        
        /// <remarks/>
        public void GetRecommendProductAsync(int count, object userState) {
            if ((this.GetRecommendProductOperationCompleted == null)) {
                this.GetRecommendProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecommendProductOperationCompleted);
            }
            this.InvokeAsync("GetRecommendProduct", new object[] {
                        count}, this.GetRecommendProductOperationCompleted, userState);
        }
        
        private void OnGetRecommendProductOperationCompleted(object arg) {
            if ((this.GetRecommendProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecommendProductCompleted(this, new GetRecommendProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecommendProductByType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetRecommendProductByType(int count, string type, int isCharge) {
            object[] results = this.Invoke("GetRecommendProductByType", new object[] {
                        count,
                        type,
                        isCharge});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRecommendProductByTypeAsync(int count, string type, int isCharge) {
            this.GetRecommendProductByTypeAsync(count, type, isCharge, null);
        }
        
        /// <remarks/>
        public void GetRecommendProductByTypeAsync(int count, string type, int isCharge, object userState) {
            if ((this.GetRecommendProductByTypeOperationCompleted == null)) {
                this.GetRecommendProductByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecommendProductByTypeOperationCompleted);
            }
            this.InvokeAsync("GetRecommendProductByType", new object[] {
                        count,
                        type,
                        isCharge}, this.GetRecommendProductByTypeOperationCompleted, userState);
        }
        
        private void OnGetRecommendProductByTypeOperationCompleted(object arg) {
            if ((this.GetRecommendProductByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecommendProductByTypeCompleted(this, new GetRecommendProductByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertOrders(string productId, string userName, string siteUrl) {
            object[] results = this.Invoke("InsertOrders", new object[] {
                        productId,
                        userName,
                        siteUrl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertOrdersAsync(string productId, string userName, string siteUrl) {
            this.InsertOrdersAsync(productId, userName, siteUrl, null);
        }
        
        /// <remarks/>
        public void InsertOrdersAsync(string productId, string userName, string siteUrl, object userState) {
            if ((this.InsertOrdersOperationCompleted == null)) {
                this.InsertOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOrdersOperationCompleted);
            }
            this.InvokeAsync("InsertOrders", new object[] {
                        productId,
                        userName,
                        siteUrl}, this.InsertOrdersOperationCompleted, userState);
        }
        
        private void OnInsertOrdersOperationCompleted(object arg) {
            if ((this.InsertOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertOrdersCompleted(this, new InsertOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyPlugins", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetMyPlugins(string sn) {
            object[] results = this.Invoke("GetMyPlugins", new object[] {
                        sn});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyPluginsAsync(string sn) {
            this.GetMyPluginsAsync(sn, null);
        }
        
        /// <remarks/>
        public void GetMyPluginsAsync(string sn, object userState) {
            if ((this.GetMyPluginsOperationCompleted == null)) {
                this.GetMyPluginsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyPluginsOperationCompleted);
            }
            this.InvokeAsync("GetMyPlugins", new object[] {
                        sn}, this.GetMyPluginsOperationCompleted, userState);
        }
        
        private void OnGetMyPluginsOperationCompleted(object arg) {
            if ((this.GetMyPluginsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyPluginsCompleted(this, new GetMyPluginsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlugins", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetPlugins(int type, int count) {
            object[] results = this.Invoke("GetPlugins", new object[] {
                        type,
                        count});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPluginsAsync(int type, int count) {
            this.GetPluginsAsync(type, count, null);
        }
        
        /// <remarks/>
        public void GetPluginsAsync(int type, int count, object userState) {
            if ((this.GetPluginsOperationCompleted == null)) {
                this.GetPluginsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPluginsOperationCompleted);
            }
            this.InvokeAsync("GetPlugins", new object[] {
                        type,
                        count}, this.GetPluginsOperationCompleted, userState);
        }
        
        private void OnGetPluginsOperationCompleted(object arg) {
            if ((this.GetPluginsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPluginsCompleted(this, new GetPluginsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPlugins", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] QueryPlugins(string keyword) {
            object[] results = this.Invoke("QueryPlugins", new object[] {
                        keyword});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryPluginsAsync(string keyword) {
            this.QueryPluginsAsync(keyword, null);
        }
        
        /// <remarks/>
        public void QueryPluginsAsync(string keyword, object userState) {
            if ((this.QueryPluginsOperationCompleted == null)) {
                this.QueryPluginsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPluginsOperationCompleted);
            }
            this.InvokeAsync("QueryPlugins", new object[] {
                        keyword}, this.QueryPluginsOperationCompleted, userState);
        }
        
        private void OnQueryPluginsOperationCompleted(object arg) {
            if ((this.QueryPluginsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPluginsCompleted(this, new QueryPluginsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckSite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CheckSite(string loginName, string password, string url) {
            object[] results = this.Invoke("CheckSite", new object[] {
                        loginName,
                        password,
                        url});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckSiteAsync(string loginName, string password, string url) {
            this.CheckSiteAsync(loginName, password, url, null);
        }
        
        /// <remarks/>
        public void CheckSiteAsync(string loginName, string password, string url, object userState) {
            if ((this.CheckSiteOperationCompleted == null)) {
                this.CheckSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSiteOperationCompleted);
            }
            this.InvokeAsync("CheckSite", new object[] {
                        loginName,
                        password,
                        url}, this.CheckSiteOperationCompleted, userState);
        }
        
        private void OnCheckSiteOperationCompleted(object arg) {
            if ((this.CheckSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSiteCompleted(this, new CheckSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisteSite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RegisteSite(string loginName, string password, string url, string siteName) {
            object[] results = this.Invoke("RegisteSite", new object[] {
                        loginName,
                        password,
                        url,
                        siteName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RegisteSiteAsync(string loginName, string password, string url, string siteName) {
            this.RegisteSiteAsync(loginName, password, url, siteName, null);
        }
        
        /// <remarks/>
        public void RegisteSiteAsync(string loginName, string password, string url, string siteName, object userState) {
            if ((this.RegisteSiteOperationCompleted == null)) {
                this.RegisteSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisteSiteOperationCompleted);
            }
            this.InvokeAsync("RegisteSite", new object[] {
                        loginName,
                        password,
                        url,
                        siteName}, this.RegisteSiteOperationCompleted, userState);
        }
        
        private void OnRegisteSiteOperationCompleted(object arg) {
            if ((this.RegisteSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisteSiteCompleted(this, new RegisteSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadRegistedProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] LoadRegistedProducts(string loginName, string password, string url) {
            object[] results = this.Invoke("LoadRegistedProducts", new object[] {
                        loginName,
                        password,
                        url});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadRegistedProductsAsync(string loginName, string password, string url) {
            this.LoadRegistedProductsAsync(loginName, password, url, null);
        }
        
        /// <remarks/>
        public void LoadRegistedProductsAsync(string loginName, string password, string url, object userState) {
            if ((this.LoadRegistedProductsOperationCompleted == null)) {
                this.LoadRegistedProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRegistedProductsOperationCompleted);
            }
            this.InvokeAsync("LoadRegistedProducts", new object[] {
                        loginName,
                        password,
                        url}, this.LoadRegistedProductsOperationCompleted, userState);
        }
        
        private void OnLoadRegistedProductsOperationCompleted(object arg) {
            if ((this.LoadRegistedProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRegistedProductsCompleted(this, new LoadRegistedProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadNotRegistedProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderDetailModel[] LoadNotRegistedProducts(string loginName, string password, string url) {
            object[] results = this.Invoke("LoadNotRegistedProducts", new object[] {
                        loginName,
                        password,
                        url});
            return ((OrderDetailModel[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadNotRegistedProductsAsync(string loginName, string password, string url) {
            this.LoadNotRegistedProductsAsync(loginName, password, url, null);
        }
        
        /// <remarks/>
        public void LoadNotRegistedProductsAsync(string loginName, string password, string url, object userState) {
            if ((this.LoadNotRegistedProductsOperationCompleted == null)) {
                this.LoadNotRegistedProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadNotRegistedProductsOperationCompleted);
            }
            this.InvokeAsync("LoadNotRegistedProducts", new object[] {
                        loginName,
                        password,
                        url}, this.LoadNotRegistedProductsOperationCompleted, userState);
        }
        
        private void OnLoadNotRegistedProductsOperationCompleted(object arg) {
            if ((this.LoadNotRegistedProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadNotRegistedProductsCompleted(this, new LoadNotRegistedProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisteProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisteProduct(string loginName, string password, string url, string orderDetailID) {
            object[] results = this.Invoke("RegisteProduct", new object[] {
                        loginName,
                        password,
                        url,
                        orderDetailID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisteProductAsync(string loginName, string password, string url, string orderDetailID) {
            this.RegisteProductAsync(loginName, password, url, orderDetailID, null);
        }
        
        /// <remarks/>
        public void RegisteProductAsync(string loginName, string password, string url, string orderDetailID, object userState) {
            if ((this.RegisteProductOperationCompleted == null)) {
                this.RegisteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisteProductOperationCompleted);
            }
            this.InvokeAsync("RegisteProduct", new object[] {
                        loginName,
                        password,
                        url,
                        orderDetailID}, this.RegisteProductOperationCompleted, userState);
        }
        
        private void OnRegisteProductOperationCompleted(object arg) {
            if ((this.RegisteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisteProductCompleted(this, new RegisteProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EncryptPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncryptPassword(string loginName, string password) {
            object[] results = this.Invoke("EncryptPassword", new object[] {
                        loginName,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptPasswordAsync(string loginName, string password) {
            this.EncryptPasswordAsync(loginName, password, null);
        }
        
        /// <remarks/>
        public void EncryptPasswordAsync(string loginName, string password, object userState) {
            if ((this.EncryptPasswordOperationCompleted == null)) {
                this.EncryptPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptPasswordOperationCompleted);
            }
            this.InvokeAsync("EncryptPassword", new object[] {
                        loginName,
                        password}, this.EncryptPasswordOperationCompleted, userState);
        }
        
        private void OnEncryptPasswordOperationCompleted(object arg) {
            if ((this.EncryptPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptPasswordCompleted(this, new EncryptPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StoreModel {
        
        private int stateField;
        
        private string idField;
        
        private string accountIDField;
        
        private string userNameField;
        
        private string storeNameField;
        
        private string classIDField;
        
        private string storeIntroField;
        
        private string companyNameField;
        
        private string addressField;
        
        private string bulletinField;
        
        private System.DateTime createdField;
        
        private System.DateTime updatedField;
        
        private string faceField;
        
        private int shopTypeField;
        
        private int levelField;
        
        private int clicksField;
        
        private bool originalField;
        
        private bool freeRepairField;
        
        private decimal incomeField;
        
        private bool realNameValidateField;
        
        private bool emailValidateField;
        
        private string scopeOfBusinessField;
        
        private string goodAtTechnologyField;
        
        private string urlField;
        
        private string technicalLevelField;
        
        private int salesField;
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string StoreIntro {
            get {
                return this.storeIntroField;
            }
            set {
                this.storeIntroField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Bulletin {
            get {
                return this.bulletinField;
            }
            set {
                this.bulletinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public string Face {
            get {
                return this.faceField;
            }
            set {
                this.faceField = value;
            }
        }
        
        /// <remarks/>
        public int ShopType {
            get {
                return this.shopTypeField;
            }
            set {
                this.shopTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public int Clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
            }
        }
        
        /// <remarks/>
        public bool Original {
            get {
                return this.originalField;
            }
            set {
                this.originalField = value;
            }
        }
        
        /// <remarks/>
        public bool FreeRepair {
            get {
                return this.freeRepairField;
            }
            set {
                this.freeRepairField = value;
            }
        }
        
        /// <remarks/>
        public decimal Income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
            }
        }
        
        /// <remarks/>
        public bool RealNameValidate {
            get {
                return this.realNameValidateField;
            }
            set {
                this.realNameValidateField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailValidate {
            get {
                return this.emailValidateField;
            }
            set {
                this.emailValidateField = value;
            }
        }
        
        /// <remarks/>
        public string ScopeOfBusiness {
            get {
                return this.scopeOfBusinessField;
            }
            set {
                this.scopeOfBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string GoodAtTechnology {
            get {
                return this.goodAtTechnologyField;
            }
            set {
                this.goodAtTechnologyField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string TechnicalLevel {
            get {
                return this.technicalLevelField;
            }
            set {
                this.technicalLevelField = value;
            }
        }
        
        /// <remarks/>
        public int Sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDetailModel {
        
        private string idField;
        
        private System.DateTime createdField;
        
        private System.DateTime updatedField;
        
        private string orderIDField;
        
        private string productIDField;
        
        private int quatityField;
        
        private int currentStateField;
        
        private string userIDField;
        
        private string storeIDField;
        
        private string sellerUNameField;
        
        private int hasScoreField;
        
        private int registBalanceField;
        
        private ProductInfo productDetailInfoField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quatity {
            get {
                return this.quatityField;
            }
            set {
                this.quatityField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentState {
            get {
                return this.currentStateField;
            }
            set {
                this.currentStateField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string SellerUName {
            get {
                return this.sellerUNameField;
            }
            set {
                this.sellerUNameField = value;
            }
        }
        
        /// <remarks/>
        public int HasScore {
            get {
                return this.hasScoreField;
            }
            set {
                this.hasScoreField = value;
            }
        }
        
        /// <remarks/>
        public int RegistBalance {
            get {
                return this.registBalanceField;
            }
            set {
                this.registBalanceField = value;
            }
        }
        
        /// <remarks/>
        public ProductInfo ProductDetailInfo {
            get {
                return this.productDetailInfoField;
            }
            set {
                this.productDetailInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductInfo {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private decimal priceField;
        
        private string urlField;
        
        private string versionField;
        
        private string authorField;
        
        private string thumbnailField;
        
        private string pageUrlField;
        
        private int salesField;
        
        private System.DateTime updatedField;
        
        private int levelField;
        
        private int isRecommendedField;
        
        private string ownerIDField;
        
        private string productCategoryField;
        
        private int pointField;
        
        private string sellerUNameField;
        
        private int authorTypeField;
        
        private string versionCmsField;
        
        private int isChargeField;
        
        private string productImgField;
        
        private string productUrlField;
        
        private string productIntroField;
        
        private System.DateTime createdField;
        
        private int stateField;
        
        private int isDeletedField;
        
        private string keywordField;
        
        private string productENameField;
        
        private string accountIDField;
        
        private int isPassedField;
        
        private string productSizeField;
        
        private string storeUrlField;
        
        private string storeNameField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
        
        /// <remarks/>
        public string PageUrl {
            get {
                return this.pageUrlField;
            }
            set {
                this.pageUrlField = value;
            }
        }
        
        /// <remarks/>
        public int Sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public int IsRecommended {
            get {
                return this.isRecommendedField;
            }
            set {
                this.isRecommendedField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public string SellerUName {
            get {
                return this.sellerUNameField;
            }
            set {
                this.sellerUNameField = value;
            }
        }
        
        /// <remarks/>
        public int AuthorType {
            get {
                return this.authorTypeField;
            }
            set {
                this.authorTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VersionCms {
            get {
                return this.versionCmsField;
            }
            set {
                this.versionCmsField = value;
            }
        }
        
        /// <remarks/>
        public int IsCharge {
            get {
                return this.isChargeField;
            }
            set {
                this.isChargeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductImg {
            get {
                return this.productImgField;
            }
            set {
                this.productImgField = value;
            }
        }
        
        /// <remarks/>
        public string ProductUrl {
            get {
                return this.productUrlField;
            }
            set {
                this.productUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ProductIntro {
            get {
                return this.productIntroField;
            }
            set {
                this.productIntroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public string Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public string ProductEName {
            get {
                return this.productENameField;
            }
            set {
                this.productENameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public int IsPassed {
            get {
                return this.isPassedField;
            }
            set {
                this.isPassedField = value;
            }
        }
        
        /// <remarks/>
        public string ProductSize {
            get {
                return this.productSizeField;
            }
            set {
                this.productSizeField = value;
            }
        }
        
        /// <remarks/>
        public string StoreUrl {
            get {
                return this.storeUrlField;
            }
            set {
                this.storeUrlField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRecommendStoreCompletedEventHandler(object sender, GetRecommendStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecommendStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecommendStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoreModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoreModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRecommendProductCompletedEventHandler(object sender, GetRecommendProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecommendProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecommendProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRecommendProductByTypeCompletedEventHandler(object sender, GetRecommendProductByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecommendProductByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecommendProductByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertOrdersCompletedEventHandler(object sender, InsertOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMyPluginsCompletedEventHandler(object sender, GetMyPluginsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyPluginsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyPluginsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPluginsCompletedEventHandler(object sender, GetPluginsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPluginsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPluginsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryPluginsCompletedEventHandler(object sender, QueryPluginsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPluginsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPluginsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckSiteCompletedEventHandler(object sender, CheckSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegisteSiteCompletedEventHandler(object sender, RegisteSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisteSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisteSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoadRegistedProductsCompletedEventHandler(object sender, LoadRegistedProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRegistedProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRegistedProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoadNotRegistedProductsCompletedEventHandler(object sender, LoadNotRegistedProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadNotRegistedProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadNotRegistedProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderDetailModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderDetailModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegisteProductCompletedEventHandler(object sender, RegisteProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EncryptPasswordCompletedEventHandler(object sender, EncryptPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591