//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3082
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace We7.CMS.Web.User.Controls {
    
    
    public partial class Account_Extent {

        protected global::We7.Model.UI.Panel.system.SimpleEditorPanel EditorPanel1;
    }
}
