//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace We7.CMS.WebControls.WD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WDWebServiceSoap", Namespace="http://www.we7.cn/")]
    public partial class WDWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWDSiteConfigInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebSiteTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebSitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSiteSMUrlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WDWebService() {
            this.Url = global::We7.CMS.WebControls.Properties.Settings.Default.We7_CMS_WebControls_WD_WDWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event GetServerTimeCompletedEventHandler GetServerTimeCompleted;
        
        /// <remarks/>
        public event GetWDSiteConfigInfoCompletedEventHandler GetWDSiteConfigInfoCompleted;
        
        /// <remarks/>
        public event GetWebSiteCompletedEventHandler GetWebSiteCompleted;
        
        /// <remarks/>
        public event GetWebSiteTreeCompletedEventHandler GetWebSiteTreeCompleted;
        
        /// <remarks/>
        public event GetWebSitesCompletedEventHandler GetWebSitesCompleted;
        
        /// <remarks/>
        public event GetSiteSMUrlCompletedEventHandler GetSiteSMUrlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/Ping", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetServerTime", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetServerTime() {
            object[] results = this.Invoke("GetServerTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerTimeAsync() {
            this.GetServerTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetServerTimeAsync(object userState) {
            if ((this.GetServerTimeOperationCompleted == null)) {
                this.GetServerTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerTimeOperationCompleted);
            }
            this.InvokeAsync("GetServerTime", new object[0], this.GetServerTimeOperationCompleted, userState);
        }
        
        private void OnGetServerTimeOperationCompleted(object arg) {
            if ((this.GetServerTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerTimeCompleted(this, new GetServerTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetWDSiteConfigInfo", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SiteConfigInfo GetWDSiteConfigInfo() {
            object[] results = this.Invoke("GetWDSiteConfigInfo", new object[0]);
            return ((SiteConfigInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetWDSiteConfigInfoAsync() {
            this.GetWDSiteConfigInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetWDSiteConfigInfoAsync(object userState) {
            if ((this.GetWDSiteConfigInfoOperationCompleted == null)) {
                this.GetWDSiteConfigInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWDSiteConfigInfoOperationCompleted);
            }
            this.InvokeAsync("GetWDSiteConfigInfo", new object[0], this.GetWDSiteConfigInfoOperationCompleted, userState);
        }
        
        private void OnGetWDSiteConfigInfoOperationCompleted(object arg) {
            if ((this.GetWDSiteConfigInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWDSiteConfigInfoCompleted(this, new GetWDSiteConfigInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetWebSite", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebSite GetWebSite(string siteID) {
            object[] results = this.Invoke("GetWebSite", new object[] {
                        siteID});
            return ((WebSite)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebSiteAsync(string siteID) {
            this.GetWebSiteAsync(siteID, null);
        }
        
        /// <remarks/>
        public void GetWebSiteAsync(string siteID, object userState) {
            if ((this.GetWebSiteOperationCompleted == null)) {
                this.GetWebSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebSiteOperationCompleted);
            }
            this.InvokeAsync("GetWebSite", new object[] {
                        siteID}, this.GetWebSiteOperationCompleted, userState);
        }
        
        private void OnGetWebSiteOperationCompleted(object arg) {
            if ((this.GetWebSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebSiteCompleted(this, new GetWebSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetWebSiteTree", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebSite GetWebSiteTree(string siteID, bool children) {
            object[] results = this.Invoke("GetWebSiteTree", new object[] {
                        siteID,
                        children});
            return ((WebSite)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebSiteTreeAsync(string siteID, bool children) {
            this.GetWebSiteTreeAsync(siteID, children, null);
        }
        
        /// <remarks/>
        public void GetWebSiteTreeAsync(string siteID, bool children, object userState) {
            if ((this.GetWebSiteTreeOperationCompleted == null)) {
                this.GetWebSiteTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebSiteTreeOperationCompleted);
            }
            this.InvokeAsync("GetWebSiteTree", new object[] {
                        siteID,
                        children}, this.GetWebSiteTreeOperationCompleted, userState);
        }
        
        private void OnGetWebSiteTreeOperationCompleted(object arg) {
            if ((this.GetWebSiteTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebSiteTreeCompleted(this, new GetWebSiteTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetWebSites", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebSite[] GetWebSites() {
            object[] results = this.Invoke("GetWebSites", new object[0]);
            return ((WebSite[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWebSitesAsync() {
            this.GetWebSitesAsync(null);
        }
        
        /// <remarks/>
        public void GetWebSitesAsync(object userState) {
            if ((this.GetWebSitesOperationCompleted == null)) {
                this.GetWebSitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebSitesOperationCompleted);
            }
            this.InvokeAsync("GetWebSites", new object[0], this.GetWebSitesOperationCompleted, userState);
        }
        
        private void OnGetWebSitesOperationCompleted(object arg) {
            if ((this.GetWebSitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebSitesCompleted(this, new GetWebSitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.we7.cn/GetSiteSMUrl", RequestNamespace="http://www.we7.cn/", ResponseNamespace="http://www.we7.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSiteSMUrl(string siteID) {
            object[] results = this.Invoke("GetSiteSMUrl", new object[] {
                        siteID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiteSMUrlAsync(string siteID) {
            this.GetSiteSMUrlAsync(siteID, null);
        }
        
        /// <remarks/>
        public void GetSiteSMUrlAsync(string siteID, object userState) {
            if ((this.GetSiteSMUrlOperationCompleted == null)) {
                this.GetSiteSMUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiteSMUrlOperationCompleted);
            }
            this.InvokeAsync("GetSiteSMUrl", new object[] {
                        siteID}, this.GetSiteSMUrlOperationCompleted, userState);
        }
        
        private void OnGetSiteSMUrlOperationCompleted(object arg) {
            if ((this.GetSiteSMUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiteSMUrlCompleted(this, new GetSiteSMUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.we7.cn/")]
    public partial class SiteConfigInfo {
        
        private string wDWebUrlField;
        
        private bool siteGroupEnabledField;
        
        private string siteIDField;
        
        private string companyIDField;
        
        private string companyNameField;
        
        private string compangDescriptionField;
        
        private string rootUrlField;
        
        private string webGroupSericeKeyField;
        
        private string webGroupServiceUrlField;
        
        private string informationServiceUrlField;
        
        private string administratorIDField;
        
        private string administratorKeyField;
        
        private bool isPasswordHashedField;
        
        private string ssoUrlField;
        
        private string ssoServernameField;
        
        private string ssoUsernameField;
        
        private string ssoPasswordField;
        
        private string ssoDomainField;
        
        private string ssoWdIDField;
        
        private string aDUrlField;
        
        /// <remarks/>
        public string WDWebUrl {
            get {
                return this.wDWebUrlField;
            }
            set {
                this.wDWebUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool SiteGroupEnabled {
            get {
                return this.siteGroupEnabledField;
            }
            set {
                this.siteGroupEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompangDescription {
            get {
                return this.compangDescriptionField;
            }
            set {
                this.compangDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RootUrl {
            get {
                return this.rootUrlField;
            }
            set {
                this.rootUrlField = value;
            }
        }
        
        /// <remarks/>
        public string WebGroupSericeKey {
            get {
                return this.webGroupSericeKeyField;
            }
            set {
                this.webGroupSericeKeyField = value;
            }
        }
        
        /// <remarks/>
        public string WebGroupServiceUrl {
            get {
                return this.webGroupServiceUrlField;
            }
            set {
                this.webGroupServiceUrlField = value;
            }
        }
        
        /// <remarks/>
        public string InformationServiceUrl {
            get {
                return this.informationServiceUrlField;
            }
            set {
                this.informationServiceUrlField = value;
            }
        }
        
        /// <remarks/>
        public string AdministratorID {
            get {
                return this.administratorIDField;
            }
            set {
                this.administratorIDField = value;
            }
        }
        
        /// <remarks/>
        public string AdministratorKey {
            get {
                return this.administratorKeyField;
            }
            set {
                this.administratorKeyField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPasswordHashed {
            get {
                return this.isPasswordHashedField;
            }
            set {
                this.isPasswordHashedField = value;
            }
        }
        
        /// <remarks/>
        public string SsoUrl {
            get {
                return this.ssoUrlField;
            }
            set {
                this.ssoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SsoServername {
            get {
                return this.ssoServernameField;
            }
            set {
                this.ssoServernameField = value;
            }
        }
        
        /// <remarks/>
        public string SsoUsername {
            get {
                return this.ssoUsernameField;
            }
            set {
                this.ssoUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string SsoPassword {
            get {
                return this.ssoPasswordField;
            }
            set {
                this.ssoPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SsoDomain {
            get {
                return this.ssoDomainField;
            }
            set {
                this.ssoDomainField = value;
            }
        }
        
        /// <remarks/>
        public string SsoWdID {
            get {
                return this.ssoWdIDField;
            }
            set {
                this.ssoWdIDField = value;
            }
        }
        
        /// <remarks/>
        public string ADUrl {
            get {
                return this.aDUrlField;
            }
            set {
                this.aDUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.we7.cn/")]
    public partial class WebSite {
        
        private string idField;
        
        private string parentIDField;
        
        private string serviceIDField;
        
        private int indexField;
        
        private string descriptionField;
        
        private System.DateTime createdField;
        
        private System.DateTime updatedField;
        
        private SiteStates stateField;
        
        private int initLockField;
        
        private int maximumField;
        
        private int usedField;
        
        private System.DateTime overdueField;
        
        private string cpuIDField;
        
        private string hdIDField;
        
        private string websitePathField;
        
        private string enumStateField;
        
        private string aliasField;
        
        private string fullPathField;
        
        private string urlField;
        
        private WebSite[] childrenField;
        
        private string nameField;
        
        private int portField;
        
        private string zoneNameField;
        
        private string siteIPField;
        
        private string siteIisIDField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public SiteStates State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int InitLock {
            get {
                return this.initLockField;
            }
            set {
                this.initLockField = value;
            }
        }
        
        /// <remarks/>
        public int Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        public int Used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Overdue {
            get {
                return this.overdueField;
            }
            set {
                this.overdueField = value;
            }
        }
        
        /// <remarks/>
        public string CpuID {
            get {
                return this.cpuIDField;
            }
            set {
                this.cpuIDField = value;
            }
        }
        
        /// <remarks/>
        public string HdID {
            get {
                return this.hdIDField;
            }
            set {
                this.hdIDField = value;
            }
        }
        
        /// <remarks/>
        public string WebsitePath {
            get {
                return this.websitePathField;
            }
            set {
                this.websitePathField = value;
            }
        }
        
        /// <remarks/>
        public string EnumState {
            get {
                return this.enumStateField;
            }
            set {
                this.enumStateField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string FullPath {
            get {
                return this.fullPathField;
            }
            set {
                this.fullPathField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public WebSite[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string ZoneName {
            get {
                return this.zoneNameField;
            }
            set {
                this.zoneNameField = value;
            }
        }
        
        /// <remarks/>
        public string SiteIP {
            get {
                return this.siteIPField;
            }
            set {
                this.siteIPField = value;
            }
        }
        
        /// <remarks/>
        public string SiteIisID {
            get {
                return this.siteIisIDField;
            }
            set {
                this.siteIisIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.we7.cn/")]
    public enum SiteStates {
        
        /// <remarks/>
        Starting,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Pasuing,
        
        /// <remarks/>
        Pasued,
        
        /// <remarks/>
        Continuing,
        
        /// <remarks/>
        Separating,
        
        /// <remarks/>
        Separated,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        UnResponse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServerTimeCompletedEventHandler(object sender, GetServerTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWDSiteConfigInfoCompletedEventHandler(object sender, GetWDSiteConfigInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWDSiteConfigInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWDSiteConfigInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SiteConfigInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SiteConfigInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWebSiteCompletedEventHandler(object sender, GetWebSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebSite Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebSite)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWebSiteTreeCompletedEventHandler(object sender, GetWebSiteTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebSiteTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebSiteTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebSite Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebSite)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWebSitesCompletedEventHandler(object sender, GetWebSitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebSitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebSitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebSite[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebSite[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSiteSMUrlCompletedEventHandler(object sender, GetSiteSMUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiteSMUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiteSMUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591